### ISSUE TITLE
运行时会在signin步骤遇到错误

### ISSUE THREAD

**Issue by MBR000** [MikasaEureka/BUPT_nCoV_easily_fixed_form#2]
```
Traceback (most recent call last):
  File "/home/runner/work/BUPT_nCoV_easily_fixed_form/BUPT_nCoV_easily_fixed_form/auto.py", line 13, in <module>
    from server_bot import *
  File "/home/runner/work/BUPT_nCoV_easily_fixed_form/BUPT_nCoV_easily_fixed_form/server_bot.py", line 2[6](https://github.com/MBR000/BUPT_nCoV_easily_fixed_form/runs/6150317305?check_suite_focus=true#step:5:6), in <module>
    USERs = eval(os.environ['USERs'])
  File "<string>", line 0
    
SyntaxError: unexpected EOF while parsing
Error: Process completed with exit code 1.
```
运行时会在signin步骤遇到错误，问题出在哪里呢，应该如何调整

**Comment by MikasaEureka** [comment]
应该是没有加中括号导致的

**Comment by MBR000** [comment]
您是说把 
USERs: [('20********','key','nickname','0')]AREA: ["北京市 海淀区"]SERVER_KEY: ['*********']
三个属性全装在中括号里面么


我这样对么，但是依然有错












梅皓

北京邮电大学/本科生/计算机学院（国家示范性软件学院）



18702869102

北京




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Apr 25, 2022 11:33 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [MikasaEureka/BUPT_nCoV_easily_fixed_form] 运行时会在signin步骤遇到错误 (Issue #2)

&nbsp;



 
应该是没有加中括号导致的

**Comment by MikasaEureka** [comment]
不是，是分别有一个[]
这是三个变量
变量名分别是USERs、AREA、SERVER_KEY
对应的值分别为 [('20********','key','nickname','0')]、 ["北京市 海淀区"]、['*********']

**Comment by MikasaEureka** [comment]
是三个secret
分别是
USERs
 对应的值为     [('20********','key','nickname','0')]
AREA
 对应的值为     ["北京市 海淀区"]
SERVER_KEY
 对应的值为     ['*********']

**Comment by MikasaEureka** [comment]
有一个事情，，，我看不到图片的

**Comment by MikasaEureka** [comment]
你重新发一下图片吧，github默认是没有图片的。。。



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MikasaEureka/BUPT_nCoV_easily_fixed_form"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 晚上11:53
***@***.***&gt;;
抄送:&nbsp;"Kal ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MikasaEureka/BUPT_nCoV_easily_fixed_form] 运行时会在signin步骤遇到错误 (Issue #2)





 这样填写secret对么？ 
 或者请赐教怎样填写的格式才对 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 梅皓 
 
 北京邮电大学/本科生/计算机学院（国家示范性软件学院） 
 
 
 
 18702869102 
 
 北京 
 
 
 
 
 &amp;nbsp; 
 &amp;nbsp; 
 &amp;nbsp; 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------ 
 From: ***@***.***&amp;gt;; 
 Date: &amp;nbsp;Mon, Apr 25, 2022 11:49 PM 
 To: ***@***.***&amp;gt;;  
 Cc: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 Subject: &amp;nbsp;Re: [MikasaEureka/BUPT_nCoV_easily_fixed_form] 运行时会在signin步骤遇到错误 (Issue #2) 
 
 &amp;nbsp; 
 
 
 
   
 不是，是分别有一个[] 
  这是三个变量 
  变量名分别是USERs、AREA、SERVER_KEY 
  对应的值分别为 [('20********','key','nickname','0')]、 ["北京市 海淀区"]、['*********']

**Comment by MBR000** [comment]
谢谢，您说三个secret我就理解了。
现在已经好了

解决办法就是把三个属性分别装在三个secret中

（我一直用邮箱回复的，没注意到图片这事，对不起啊）

**Comment by MBR000** [comment]
> 你重新发一下图片吧，github默认是没有图片的。。。 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MikasaEureka/BUPT_nCoV_easily_fixed_form" ***@***.***&gt;; 发送时间:&nbsp;2022年4月25日(星期一) 晚上11:53 ***@***.***&gt;; 抄送:&nbsp;"Kal ***@***.******@***.***&gt;; 主题:&nbsp;Re: [MikasaEureka/BUPT_nCoV_easily_fixed_form] 运行时会在signin步骤遇到错误 (Issue #2) 这样填写secret对么？ 或者请赐教怎样填写的格式才对 梅皓 北京邮电大学/本科生/计算机学院（国家示范性软件学院） 18702869102 北京 &amp;nbsp; &amp;nbsp; &amp;nbsp; ------------------&amp;nbsp;Original&amp;nbsp;------------------ From: ***@***.***&amp;gt;; Date: &amp;nbsp;Mon, Apr 25, 2022 11:49 PM To: ***@***.***&amp;gt;; Cc: ***@***.***&amp;gt;; ***@***.***&amp;gt;; Subject: &amp;nbsp;Re: [MikasaEureka/BUPT_nCoV_easily_fixed_form] 运行时会在signin步骤遇到错误 (Issue #2) &amp;nbsp; 不是，是分别有一个[] 这是三个变量 变量名分别是USERs、AREA、SERVER_KEY 对应的值分别为 [('20********','key','nickname','0')]、 ["北京市 海淀区"]、['*********'] — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

**Comment by MikasaEureka** [comment]
没事，帮到你就好
